spring:
  profiles: integrtests
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    database-platform:
  datasource:
    database-name: postgres
    url: jdbc:postgresql://localhost:5432/${spring.datasource.database-name}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml

appConfig:
  environment: ${spring.profiles}
  dbDriver: ${spring.datasource.driver-class-name}
  dbUrl: ${spring.datasource.url}
  dbName: ${spring.datasource.database-name}