spring:
  application:
    name: cassette
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/cassette
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
