spring:
  application:
    name: cassette
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
#  TODO need to configure the Liquibase
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/${spring.datasource.database-name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: none
