spring:
  profiles: functests
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
    database-platform:
  datasource:
    database-name: cassette
    url: jdbc:mysql://localhost:3306/${spring.datasource.database-name}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

appConfig:
  environment: ${spring.profiles}
  dbDriver: ${spring.datasource.driver-class-name}
  dbUrl: ${spring.datasource.url}
  dbName: ${spring.datasource.database-name}
