-- MySQL Script generated by MySQL Workbench
-- Thu Apr  8 15:13:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema QueueManager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema QueueManager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `QueueManager` DEFAULT CHARACTER SET utf8 ;
USE `QueueManager` ;

-- -----------------------------------------------------
-- Table `QueueManager`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`accounts` (
  `idcredentials` INT NOT NULL,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idcredentials`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`broker` (
  `idbroker` INT NOT NULL,
  `brokername` VARCHAR(128) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `description` TEXT(512) NULL,
  `credentials_idcredentials` INT NOT NULL,
  PRIMARY KEY (`idbroker`),
  INDEX `fk_broker_credentials1_idx` (`credentials_idcredentials` ASC) VISIBLE,
  UNIQUE INDEX `brokername_UNIQUE` (`brokername` ASC) VISIBLE,
  CONSTRAINT `fk_broker_credentials1`
    FOREIGN KEY (`credentials_idcredentials`)
    REFERENCES `QueueManager`.`accounts` (`idcredentials`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`status` (
  `statis_id` INT NOT NULL,
  `code` INT NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`statis_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`message` (
  `idmessage` INT NOT NULL,
  `path` VARCHAR(300) NOT NULL,
  `sendtime` DATETIME NULL,
  `broker_idbroker` INT NOT NULL,
  `status_statis_id` INT NOT NULL,
  `queue` VARCHAR(300) NULL,
  PRIMARY KEY (`idmessage`),
  INDEX `fk_message_broker1_idx` (`broker_idbroker` ASC) VISIBLE,
  INDEX `fk_message_status1_idx` (`status_statis_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_broker1`
    FOREIGN KEY (`broker_idbroker`)
    REFERENCES `QueueManager`.`broker` (`idbroker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_status1`
    FOREIGN KEY (`status_statis_id`)
    REFERENCES `QueueManager`.`status` (`statis_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`message_to_broker_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`message_to_broker_type` (
  `message_idmessage` INT NOT NULL,
  `broker_idbroker` INT NOT NULL,
  `broker_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`broker_idbroker`, `message_idmessage`),
  INDEX `fk_message_has_broker_broker1_idx` (`broker_idbroker` ASC) VISIBLE,
  INDEX `fk_message_has_broker_message1_idx` (`message_idmessage` ASC) VISIBLE,
  CONSTRAINT `fk_message_has_broker_message1`
    FOREIGN KEY (`message_idmessage`)
    REFERENCES `QueueManager`.`message` (`idmessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_has_broker_broker1`
    FOREIGN KEY (`broker_idbroker`)
    REFERENCES `QueueManager`.`broker` (`idbroker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`topic` (
  `idtopic` INT NOT NULL,
  `topicname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`topic` (
  `idtopic` INT NOT NULL,
  `topicname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtopic`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `QueueManager`.`broker_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QueueManager`.`broker_type` (
  `id_broker_type` INT NOT NULL,
  `broker_type` VARCHAR(128) NOT NULL,
  `broker_idbroker` INT NOT NULL,
  PRIMARY KEY (`id_broker_type`),
  INDEX `fk_broker_type_broker1_idx` (`broker_idbroker` ASC) VISIBLE,
  CONSTRAINT `fk_broker_type_broker1`
    FOREIGN KEY (`broker_idbroker`)
    REFERENCES `QueueManager`.`broker` (`idbroker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
