-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 15:37:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema manager_brokers
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema manager_brokers
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `manager_brokers` DEFAULT CHARACTER SET utf8 ;
USE `manager_brokers` ;

-- -----------------------------------------------------
-- Table `manager_brokers`.`broker_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_brokers`.`broker_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `broker_type` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `broker_type_UNIQUE` (`broker_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_brokers`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_brokers`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(256) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_brokers`.`broker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_brokers`.`broker` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `address` VARCHAR(128) NOT NULL,
  `desc` VARCHAR(512) NULL,
  `broker_type_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `broker_type_id_idx` (`broker_type_id` ASC) VISIBLE,
  INDEX `account_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `broker_type_id`
    FOREIGN KEY (`broker_type_id`)
    REFERENCES `manager_brokers`.`broker_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `manager_brokers`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_brokers`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_brokers`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `code` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `manager_brokers`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `manager_brokers`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(300) NOT NULL,
  `send_time` DATETIME NULL,
  `topic` VARCHAR(300) NULL,
  `broker_id` INT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `broker_id_idx` (`broker_id` ASC) VISIBLE,
  INDEX `status_id_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `broker_id`
    FOREIGN KEY (`broker_id`)
    REFERENCES `manager_brokers`.`broker` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id`
    FOREIGN KEY (`status_id`)
    REFERENCES `manager_brokers`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
